### ISSUE TITLE
Velocity

### ISSUE THREAD

**Issue by FargoFargo** [LaihoE/demoparser#36]
Hello. Thank you very much for your work. Is it possible to add velocity (m_vecVelocity) to the player data? It can be useful for many reasons.

**Comment by LaihoE** [comment]
Hi, yes this would be nice. The problem is that m_vecVelocity was removed from source 2 demos. I assume this is because velocity is just the difference between current coordinates and coordinates last tick (no new information so save on file size). This is unfortunately quite tricky to implement as I would need to store older values (parser does not currently do that). 
Will definitely be adding this at some point.

**Comment by LaihoE** [comment]
0.14.0 now supports velocity. Be careful since im not 100% it always works correctly because demo viewer doesn't have working velocity with (cl_showpos) to check against. Values did seem reasonable tho.
