### ISSUE TITLE
format parseEvents

### ISSUE THREAD

**Issue by lobanov-vitaliy** [LaihoE/demoparser#8]
good afternoon, there used to be a response format for the function parseEvents 
```js
Array<{
  fields: Object,
  name: 'event_name',
  tick: 2131
}>
```

but now it's just an object array and it's not clear to which particular event the data belong to.

**Comment by LaihoE** [comment]
Sorry I am kinda in the middle of adding some docs and made a few changes to js side.. made 2 changes:

1.  parse_events was split into 2:
```Javascript
parse_event(str) // one event only
parse_events([str]) // multiple events
```
the parse_events is to support multiple events in one call. This split was mostly done due to Python reasons.



2.
The output was changed from:
```Javascript
  Array<{
    fields: Object
    event_name: 'bomb_planted',
    tick: 75316,
  }>
```
to:
```Javascript
  Array<{
    event_name: 'bomb_planted',
    site: 311,
    tick: 75316,
    user_name: 'player1',
    user_steamid: '765611111111111'
  }>
```
where "event_name" and "tick" are moved into the the same place as the other fields. I thought this was going to be much more elegant, but I'm happy to hear your opinion about it.

**Comment by lobanov-vitaliy** [comment]
Thank you very much, I will use your lib to write a web service, I hope the package will be maintained and updated
